name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        id: checkout

      - name: Get Version
        id: get_version
        run: shopt -s extglob && shopt -p && echo "version=${GITHUB_REF##ref/tags/?(v)}" >> $GITHUB_OUTPUT && cat $GITHUB_OUTPUT

      - name: Parse Version
        uses: madhead/semver-utils@latest
        id: parse_version
        with:
          version: ${{ steps.get_version.outputs.version }}

      - name: Debug
        id: debug
        run: echo "${{ steps.parse_version.outputs }}"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: ${{ steps.version.outputs.prerelease != '' }}

