name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        id: checkout

      - name: Get Version
        id: get_version
        run: echo "${GITHUB_REF}" | sed -E 's%^refs/tags/v?%version=%' >> $GITHUB_OUTPUT

      - name: Parse Version
        uses: madhead/semver-utils@v4
        id: parse_version
        with:
          version: ${{ steps.get_version.outputs.version }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: ${{ steps.parse_version.outputs.prerelease != '' }}

