name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        id: checkout

      - name: Get Tag
        id: tag
        run: shopt -s extglob ; echo "tag=${GITHUB_REF##ref/tags/?(v)}" >> $GITHUB_OUTPUT

      - name: Parse Version
        uses: madhead/semver-utils@latest
        id: version
        with:
          version: ${{ steps.tag.outputs.tag }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: ${{ steps.version.outputs.prerelease != '' }}

